config/routes.rb
Hub::Application.routes.draw do

  resources :old_items

  get "home/index"
  post "home/contact_create"

  get "statistics/user"
  get "statistics/media"
  
  put "admin/ban_user"
  put "admin/update_preferences"

  resources :users do
    resources :flags, only: [:index, :new, :create, :destroy]
    resources :messages, only: [:new, :create]
    
    member do
      put :check_confirm_code
      put :validate_pwd_change
    end   
  end

  resources :admin do
    collection do
      get 'flagged_events'
      get 'flagged_items'
      get 'flagged_projects'
      get 'flagged_users'
      get 'banned_users'
    end
  end

  resources :events do
    resources :flags, only: [:index, :new, :create, :destroy]
  end

  resources :items do
    collection do
      get 'myItems'
    end
    resources :flags, only: [:index, :new, :create, :destroy]
  end

  resources :projects do
    resources :flags, only: [:index, :new, :create, :destroy]
  end

  resources :news
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :search, only: [:index, :new]
  resources :sessions, only: [:new, :create, :destroy]
  resources :wish_lists

  match '/search_results', to:'search#index' 
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/forgot_pass', to: 'users#password_forgot'
  match '/new_wish_list', to: 'wish_lists#new'
  match '/gallery', to: 'projects#index'
  match "/users/:id/confirm" => "users#confirm_user", as: "confirm_signup"
  match "/users/:id/change_password" => "users#change_password", as: "change_pwd"
  match "/users/:id/userItems" => "users#userItems", as: "user_items"
  match "flag/:id/delete" => "flags#destroy", :via => [:delete]
  match "/reason" => "statistics#reason_for_deletion"
  match "/deletion_results" => "statistics#deletion_results", :via => [:put]
  match "/items/?category='Appliances'" => "items#index"
  match "/items/?category='Architectural'" => "items#index"
  match "/items/?category='Cabinets'" => "items#index"
  match "/items/?category='Electrical'" => "items#index"
  match "/items/?category='Exterior Doors'" => "items#index"
  match "/items/?category='Flooring'" => "items#index"
  match "/items/?category='Furniture'" => "items#index"
  match "/items/?category='Hardware'" => "items#index"
  match "/items/?category='Heating & Cooling'" => "items#index"
  match "/items/?category='Interior Doors'" => "items#index"
  match "/items/?category='Lumber'" => "items#index"
  match "/items/?category='Masonry, Tile & Stone'" => "items#index"
  match "/items/?category='Plumbing'" => "items#index"
  match "/items/?category='Tools'" => "items#index"
  match "/items/?category='Windows'" => "items#index"
  match "/items/?category='Other'" => "items#index"

  match '/contact', to:'home#contact', :via => [:get]
  match '/contact', to:'home#contact_create', :via => [:post]

  

  root :to => 'home#index'
  match "*a", to:'home#not_found' 

end

app/views/admin/banned_users.html.erb
<% provide(:title, 'dashboard') %>
<div class="row-fluid">

  <div class="span12 top-page">
    <h1>Admin Dashboard</h1>
  </div>

</div>

<div class="masthead">
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container" style="background-position:right top;">
        <a class="btn btn-navbar" data-toggle="collapse" data-target="#admin">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <!-- <%= image_tag 'decohub-logo-admin.png', class: "brand" %> -->
        <div id="admin" class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Priority Flags", admin_index_path %></li>
          <li><%= link_to 'Flagged Events', flagged_events_admin_index_path %> </li>
          <li><%= link_to 'Flagged Items', flagged_items_admin_index_path%></li>
          <li><%= link_to 'Flagged Projects', flagged_projects_admin_index_path%></li>
          <li><%= link_to 'Flagged Users', flagged_users_admin_index_path%></li>
          <li class="active"><%= link_to 'Banned Users', banned_users_admin_index_path%></li>
        </ul>
      </div>
      </div>
    </div>
  </div>
</div>

<h2> Banned Users </h2>
<table class = "table table-striped">
  <thead>
    <th>User Name</th>
    <th>Unban User</th>
    <th>Delete User</th>
  </thead>

<% @banned_users.each do |u| %>
  <tr>
   <td><%= link_to u['banned_user'].name, u['banned_user'] %></td>
    <% if(u['banned_user'].banned) %>
      <td><%= button_to("Reactivate",{:controller => "admin", :action => "ban_user", :user =>u['banned_user'], :ban => false},:method => :put, :confirm => "Are you sure?",:class => "btn btn-large btn-warning") %> </td>
    <% else %>
      <td><%= button_to("Ban",{:controller => "admin", :action => "ban_user", :user =>u['banned_user'], :ban => true},:method => :put, :confirm => "Are you sure?",:class => "btn btn-large btn-warning") %> </td>
    <% end %>
    <td><%= link_to 'Delete', u['banned_user'], method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-large btn-danger" %></td>
  </tr>
  
<% end %>
</table>

app/views/admin/flagged_events.html.erb
<% provide(:title, 'dashboard') %>
<div class="row-fluid">

  <div class="span12 top-page">
    <h1>Admin Dashboard</h1>
  </div>

</div>

<div class="masthead">
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container" style="background-position:right top;">
        <a class="btn btn-navbar" data-toggle="collapse" data-target="#admin">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <!-- <%= image_tag 'decohub-logo-admin.png', class: "brand" %> -->
        <div id="admin" class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Priority Flags", admin_index_path %></li>
          <li class="active"><%= link_to 'Flagged Events', flagged_events_admin_index_path %> </li>
          <li><%= link_to 'Flagged Items', flagged_items_admin_index_path%></li>
          <li><%= link_to 'Flagged Projects', flagged_projects_admin_index_path%></li>
          <li><%= link_to 'Flagged Users', flagged_users_admin_index_path%></li>
          <li><%= link_to 'Banned Users', banned_users_admin_index_path %></li>
        </ul>
      </div>
      </div>
    </div>
  </div>
</div>

<h2> Flagged Events </h2>
<table class = "table table-striped">
  <thead>
    <th>Event Name</th>
    <th>Reason</th>
    <th>Comment</th>
    <th>Reported By</th>
    <th>Delete Flag </th>
    <th>Delete Event</th>
  </thead>

<% @flagged_events.each do |e| %>
  <tr>
   <td><%= link_to e['event'].name, e['event'] %></td>
    <td><%= e['flag'].reason %></td>
    <td><%= e['flag'].comment %></td>
    <td><%= link_to e['user'].name, e['user'] %></td>
    <td><%= button_to("Delete", {:controller => "flags", :action => "destroy", :id => e['flag'].id}, :method => :delete, :confirm => "Are you sure?",:class => "btn btn-large btn-primary") %></td>
    <td><%= link_to 'Delete', e['event'], method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-large btn-danger" %></td>
  </tr>
<% end %>
</table>

app/views/admin/flagged_items.html.erb
<% provide(:title, 'dashboard') %>
<div class="row-fluid">

  <div class="span12 top-page">
    <h1>Admin Dashboard</h1>
  </div>

</div>

<div class="masthead">
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container" style="background-position:right top;">
        <a class="btn btn-navbar" data-toggle="collapse" data-target="#admin">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <!-- <%= image_tag 'decohub-logo-admin.png', class: "brand" %> -->
        <div id="admin" class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Priority Flags", admin_index_path %></li>
          <li><%= link_to 'Flagged Events', flagged_events_admin_index_path %> </li>
          <li class="active"><%= link_to 'Flagged Items', flagged_items_admin_index_path%></li>
          <li><%= link_to 'Flagged Projects', flagged_projects_admin_index_path%></li>
          <li><%= link_to 'Flagged Users', flagged_users_admin_index_path%></li>
          <li><%= link_to 'Banned Users', banned_users_admin_index_path %></li>
        </ul>
      </div>
      </div>
    </div>
  </div>
</div>

<h2> Flagged Items </h2>
<table class = "table table-striped">
  <thead>
    <th>Item Name</th>
    <th>Reason</th>
    <th>Comment</th>
    <th>Reported By</th>
    <th>Delete Flag </th>
    <th>Delete Item </th>
  </thead>

<% @flagged_items.each do |i| %>
  <tr>
    <td><%= link_to i['item'].name, i['item'] %></td>
    <td><%= i['flag'].reason %></td>
    <td><%= i['flag'].comment %></td>
    <td><%= link_to i['user'].name, i['user'] %></td>
    <td><%= button_to("Delete", {:controller => "flags", :action => "destroy", :id => i['flag'].id}, :method =>:delete, :confirm => "Are you sure?",:class => "btn btn-large btn-primary") %></td>
    <td><%= link_to 'Delete', i['item'], method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-large btn-danger" %></td>
  </tr>
<% end %>
</table>

app/views/admin/flagged_projects.html.erb
<% provide(:title, 'dashboard') %>
<div class="row-fluid">

  <div class="span12 top-page">
    <h1>Admin Dashboard</h1>
  </div>

</div>

<div class="masthead">
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container" style="background-position:right top;">
        <a class="btn btn-navbar" data-toggle="collapse" data-target="#admin">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <!-- <%= image_tag 'decohub-logo-admin.png', class: "brand" %> -->
        <div id="admin" class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Priority Flags", admin_index_path %></li>
          <li><%= link_to 'Flagged Events', flagged_events_admin_index_path %> </li>
          <li><%= link_to 'Flagged Items', flagged_items_admin_index_path%></li>
          <li class="active"><%= link_to 'Flagged Projects', flagged_projects_admin_index_path%></li>
          <li><%= link_to 'Flagged Users', flagged_users_admin_index_path%></li>
          <li><%= link_to 'Banned Users', banned_users_admin_index_path %></li>
        </ul>
      </div>
      </div>
    </div>
  </div>
</div>

<h2> Flagged Projects </h2>
<table class = "table table-striped">
  <thead>
    <th>Project Name</th>
    <th>Reason</th>
    <th>Comment</th>
    <th>Reported By</th>
    <th>Delete Flag </th>
    <th>Delete Project</th>
  </thead>

<% @flagged_projects.each do |p| %>
  <tr>
   <td><%= link_to p['project'].name, p['project'] %></td>
    <td><%= p['flag'].reason %></td>
    <td><%= p['flag'].comment %></td>
    <td><%= link_to p['user'].name, p['user'] %></td>
    <td><%= button_to("Delete", {:controller => "flags", :action => "destroy", :id => p['flag'].id}, :method => :delete, :confirm => "Are you sure?",:class => "btn btn-large btn-primary") %></td>
    <td><%= link_to 'Delete', p['project'], method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-large btn-danger" %></td>
  </tr>
<% end %>
</table>

app/views/admin/flagged_users.html.erb
<% provide(:title, 'dashboard') %>
<div class="row-fluid">

  <div class="span12 top-page">
    <h1>Admin Dashboard</h1>
  </div>

</div>

<div class="masthead">
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container" style="background-position:right top;">
        <a class="btn btn-navbar" data-toggle="collapse" data-target="#admin">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <!-- <%= image_tag 'decohub-logo-admin.png', class: "brand" %> -->
        <div id="admin" class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Priority Flags", admin_index_path %></li>
          <li><%= link_to 'Flagged Events', flagged_events_admin_index_path %> </li>
          <li><%= link_to 'Flagged Items', flagged_items_admin_index_path%></li>
          <li><%= link_to 'Flagged Projects', flagged_projects_admin_index_path%></li>
          <li class="active"><%= link_to 'Flagged Users', flagged_users_admin_index_path%></li>
          <li><%= link_to 'Banned Users', banned_users_admin_index_path %></li>
        </ul>
      </div>
      </div>
    </div>
  </div>
</div>

<h2> Flagged Users </h2>
<table class = "table table-striped">
  <thead>
    <th>User Name</th>
    <th>Reason</th>
    <th>Comment</th>
    <th>Reported By</th>
    <th>Delete Flag </th>
    <th>Ban User</th>
    <th>Delete User</th>
  </thead>

<% @flagged_users.each do |u| %>
  <tr>
   <td><%= link_to u['flagged_user'].name, u['flagged_user'] %></td>
    <td><%= u['flag'].reason %></td>
    <td><%= u['flag'].comment %></td>
    <td><%= link_to u['user'].name, u['user'] %></td>
    <td><%= button_to("Delete", {:controller => "flags", :action => "destroy", :id => u['flag'].id}, :method => :delete, :confirm => "Are you sure?",:class => "btn btn-large btn-primary") %></td>
    <% if(u['flagged_user'].banned) %>
      <td><%= button_to("Reactivate",{:controller => "admin", :action => "ban_user", :user =>u['flagged_user'], :ban => false},:method => :put, :confirm => "Are you sure?",:class => "btn btn-large btn-warning") %> </td>
    <% else %>
      <td><%= button_to("Ban",{:controller => "admin", :action => "ban_user", :user =>u['flagged_user'], :ban => true},:method => :put, :confirm => "Are you sure?",:class => "btn btn-large btn-warning") %> </td>
    <% end %>
    <td><%= link_to 'Delete', u['flagged_user'], method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-large btn-danger" %></td>
  </tr>
  
<% end %>
</table>

app/views/admin/index.html.erb
<% provide(:title, 'dashboard') %>
<div class="row-fluid">

  <div class="span12 top-page">
    <h1>Admin Dashboard</h1>
  </div>

</div>

<div class="masthead">
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container" style="background-position:right top;">
        <a class="btn btn-navbar" data-toggle="collapse" data-target="#admin">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <!-- <%= image_tag 'decohub-logo-admin.png', class: "brand" %> -->
        <div id="admin" class="nav-collapse">
        <ul class="nav">
          <li class="active"><%= link_to "Priority Flags", admin_index_path %></li>
          <li><%= link_to 'Flagged Events', flagged_events_admin_index_path %> </li>
          <li><%= link_to 'Flagged Items', flagged_items_admin_index_path%></li>
          <li><%= link_to 'Flagged Projects', flagged_projects_admin_index_path%></li>
          <li><%= link_to 'Flagged Users', flagged_users_admin_index_path%></li>
          <li><%= link_to 'Banned Users', banned_users_admin_index_path %></li>
        </ul>
      </div>
      </div>
    </div>
  </div>
</div>


<h2> Flagged Users </h2>
<table class = "table table-striped">
  <thead>
    <th width="66%">User</th>
    <th># of Flags</th>
  </thead>

<% @flagged_users.each do |u| %>
  <tr>
    <td><%= link_to u['user'].name, u['user'] %></td>
    <td><%= link_to u['count'], user_flags_path(u['user']) %></td>
  </tr>
<% end %>

</table>

<h2> Flagged Items </h2>
<table class = "table table-striped">
  <thead>
    <th width="66%">Item</th>
    <th># of Flags</th>
  </thead>

<% @flagged_items.each do |i| %>
  <tr>
    <td><%= link_to i['item'].name, i['item'] %></td>
    <td><%= link_to i['count'], item_flags_path(i['item']) %></td>
  </tr>
<% end %>

</table>

<h2> Flagged Events </h2>
<table class = "table table-striped">
  <thead>
    <th width="66%">Event</th>
    <th># of Flags</th>
  </thead>

<% @flagged_events.each do |e| %>
  <tr>
    <td><%= link_to e['event'].name, e['event'] %></td>
    <td><%= link_to e['count'], event_flags_path(e['event']) %></td>
  </tr>
<% end %>

</table>

<h2> Flagged Projects </h2>
<table class = "table table-striped">
  <thead>
    <th width="66%">Project</th>
    <th># of Flags</th>
  </thead>

<% @flagged_projects.each do |p| %>
  <tr>
    <td><%= link_to p['project'].name, p['project'] %></td>
    <td><%= link_to p['count'], project_flags_path(p['project']) %></td>
  </tr>
<% end %>

</table>

<%= form_for @preference, :url => { :controller => "admin", :action => "update_preferences", :id => @preference.id } do |f| %>
  <div>
    <%= check_box "preference", "preference_value" %>
    <%= label_tag(:value, "Notify me by e-mail when a flag is submitted.", :style => "display:inline") %>
  </div><br />

  <div class="actions"><%= f.submit "Update Preferences",:class => "btn btn-large btn-success" %></div>
<% end %>

<h2> Statistics </h2>
<div class="row">
<div class="span4">
  <h3>Items</h3>
  <%= link_to "Download CSV", items_path(format: "csv"), :class => "btn btn-medium btn-primary", style: "margin:8px 4px 8px 4px;" %>
  <%= link_to "Download XLS", items_path(format: "xls"), :class => "btn btn-medium btn-primary", style: "margin:8px 4px 8px 4px;" %>
</div>
<div class="span4">
  <h3>Deleted Items</h3>
  <%= link_to "Download CSV", old_items_path(format: "csv"), :class => "btn btn-medium btn-danger", style: "margin:8px 4px 8px 4px;" %>
  <%= link_to "Download XLS", old_items_path(format: "xls"), :class => "btn btn-medium btn-danger", style: "margin:8px 4px 8px 4px;" %>
</div>
</div>