config/routes.rb
Hub::Application.routes.draw do

  resources :old_items

  get "home/index"
  post "home/contact_create"

  get "statistics/user"
  get "statistics/media"
  
  put "admin/ban_user"
  put "admin/update_preferences"

  resources :users do
    resources :flags, only: [:index, :new, :create, :destroy]
    resources :messages, only: [:new, :create]
    
    member do
      put :check_confirm_code
      put :validate_pwd_change
    end   
  end

  resources :admin do
    collection do
      get 'flagged_events'
      get 'flagged_items'
      get 'flagged_projects'
      get 'flagged_users'
      get 'banned_users'
    end
  end

  resources :events do
    resources :flags, only: [:index, :new, :create, :destroy]
  end

  resources :items do
    collection do
      get 'myItems'
    end
    resources :flags, only: [:index, :new, :create, :destroy]
  end

  resources :projects do
    resources :flags, only: [:index, :new, :create, :destroy]
  end

  resources :news
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :search, only: [:index, :new]
  resources :sessions, only: [:new, :create, :destroy]
  resources :wish_lists

  match '/search_results', to:'search#index' 
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/forgot_pass', to: 'users#password_forgot'
  match '/new_wish_list', to: 'wish_lists#new'
  match '/gallery', to: 'projects#index'
  match "/users/:id/confirm" => "users#confirm_user", as: "confirm_signup"
  match "/users/:id/change_password" => "users#change_password", as: "change_pwd"
  match "/users/:id/userItems" => "users#userItems", as: "user_items"
  match "flag/:id/delete" => "flags#destroy", :via => [:delete]
  match "/reason" => "statistics#reason_for_deletion"
  match "/deletion_results" => "statistics#deletion_results", :via => [:put]
  match "/items/?category='Appliances'" => "items#index"
  match "/items/?category='Architectural'" => "items#index"
  match "/items/?category='Cabinets'" => "items#index"
  match "/items/?category='Electrical'" => "items#index"
  match "/items/?category='Exterior Doors'" => "items#index"
  match "/items/?category='Flooring'" => "items#index"
  match "/items/?category='Furniture'" => "items#index"
  match "/items/?category='Hardware'" => "items#index"
  match "/items/?category='Heating & Cooling'" => "items#index"
  match "/items/?category='Interior Doors'" => "items#index"
  match "/items/?category='Lumber'" => "items#index"
  match "/items/?category='Masonry, Tile & Stone'" => "items#index"
  match "/items/?category='Plumbing'" => "items#index"
  match "/items/?category='Tools'" => "items#index"
  match "/items/?category='Windows'" => "items#index"
  match "/items/?category='Other'" => "items#index"

  match '/contact', to:'home#contact', :via => [:get]
  match '/contact', to:'home#contact_create', :via => [:post]

  

  root :to => 'home#index'
  match "*a", to:'home#not_found' 

end

app/models/event.rb
# app/models/event.rb

# For profanity filtering
require 'obscenity/active_model'

class Event < ActiveRecord::Base
  belongs_to :user
  has_one :location, :as => :locatable, :dependent => :destroy
  has_many :flags, :as => :flaggable, :dependent => :destroy

  accepts_nested_attributes_for :location

  attr_accessible :description, :end_time, :event_date, :image, :image_cache, :remove_image, :location_attributes, :name, :start_time

  # For uploading images
  mount_uploader :image, ImageUploader

  # String sanitization
  before_validation :sanitize_event

  # Data validation
  validates :user_id, :presence => true
  validates :name, :presence => true, :obscenity => true, :length => { :maximum => 255 }
  validates :description, :presence => true, :obscenity => true
  validates :event_date, :presence => true
  validates :start_time, :presence => true

  # Ensure location is not empty
  validate :check_location
  
  # Date/Time validation
  validates_time :end_time, :after => :start_time ,:if => "!end_time.nil?", :after_message => "must be after start time"
  validates_date :event_date, :on_or_after => Date.today, :on_or_after_message => "must be on or after today"

  # Check if location is empty
  def check_location
    if self.location.address.blank?
      errors.add(:location, "can't be blank")
    end
  end

  def sanitize_event
    # Sanitize event fields unless the field is blank
    self.name = Sanitize.clean(self.name).gsub('&amp;','&').gsub('&gt;', '>') unless self.name.blank?
    self.description = Sanitize.clean(self.description).gsub('&amp;','&').gsub('&gt;', '>') unless self.description.blank?
    self.location.address = Sanitize.clean(self.location.address).gsub('&amp;','&').gsub('&gt;', '>') unless self.location.address.blank?
  end
  
end

app/controllers/events_controller.rb
# app/controllers/events_controller.rb

class EventsController < ApplicationController
  before_filter :authenticate
  # Check if the current user is signed in
  before_filter :signed_in_user, only: [:new, :create, :edit, :update, :destroy]
  # Check if the current user is the owner of the requested resource
  before_filter :correct_user, only: [:edit, :update]
  # Check if the current user has permissions to delete the requested resource
  before_filter :can_destroy, only: [:destroy]

  # GET /events
  # GET /events.json
  # Display all events
  def index
    # Find events where the date is today or a future date
    @items = Event.where('event_date >= ?',Date.today) 
    
    # Paginate all the events
    @events = @items.page(params[:page]).per(9)
    @events.sort!{|a,b| a.event_date <=> b.event_date}

    respond_to do |format|
      format.js
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /events/1
  # GET /events/1.json
  # Display a specific event
  def show
    # Find event in the DB based on "id" parameter from the current user's request
    @event = Event.find(params[:id])
    @location = @event.location

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  # New Event
  def new
    # Create a new event
    @event = Event.new
    # Set default values for event attributes
    @event.location = Location.new
    @event.start_time = Time.now
    @event.end_time = (Time.now + 60*60)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  # Edit Event
  def edit
    # Find event in the DB
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  # Create Event
  def create
    # Get the current user
    @user = current_user
    # Create the event using the parameters from the user's request
    @event = @user.events.build(params[:event])

    respond_to do |format|
      # Save the event to the DB
      # Case 1: Event saved
      if @event.save
        # Redirect the user to the event details (show) page
        # Display success message
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      # Case 2: Event not saved
      else
        # Render the new event form and display errors
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  # Update Event
  def update
    # Find event in the DB
    @event = Event.find(params[:id])

    respond_to do |format|
      # Update event in the DB
      # Case 1: Event update successful
      if @event.update_attributes(params[:event])
        # Redirect the user to the event details page
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      # Case 2: Event update unsuccessful
      else
        # Render the edit event form with errors
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  # Delete Event
  def destroy
    # Find event in the DB
    @event = Event.find(params[:id])
    # Delete event from the DB
    @event.destroy

    respond_to do |format|
      # Redirect the current user to the events index page
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private

    # Redirect the user to the events index page unless the user owns the requested resource
    def correct_user
      @event = Event.find(params[:id])
      redirect_to(events_path) unless current_user?(@event.user)
    end

    # Redirect the user to the events index page unless the user owns the requested resource or the user is an admin
    def can_destroy
      @event = Event.find(params[:id])
      redirect_to(events_path) unless current_user?(@event.user) || current_user.admin?
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="span4 event"> 
  <div class="drop-shadow lifted">
    <%= link_to event do %>
    <%= image_tag event.image_url.to_s %>
    <p class="calendar"><%= event.event_date.strftime('%d') %> <em><%= event.event_date.strftime('%b') %></em></p>
    <h4><%= event.name %></h4>
    <% end %>
    <p><b>When: </b><%= event.start_time.strftime('%I:%M %p') %>
    <% if !event.end_time.nil? %>
    to <%= event.end_time.strftime('%I:%M %p') %>
    <% end %>
  </p>
  <% if !event.location.nil? %>
  <p><b>Where:</b> <%= event.location.address %></p>
  <%end%>
  <p><b>Hosted by: </b><%= User.find(event.user_id).name %></p>
  <p><%= raw(truncate(event.description, :length=>220, :omission => (link_to "...continued", event) )) %></p>
  <%= link_to 'Show', event, :class => "btn btn-small btn-block btn-details" %>
</div> 
</div>

app/views/events/_form.html.erb
<h2>(*) Required Fields<h2>

  <%= form_for(@event) do |f| %>
  <%= render 'shared/event_error_messages' %>

  <div class="row-fluid">
    <div class="span7 item">
      <div class="drop-shadow lifted">
        <div class="field">
          <%= f.label :image %>
          <% if @event.image? %>
          <%= image_tag(@event.image_url) %>
          <div>
            <br />
            <%= f.check_box :remove_image %>
            <%= f.label :remove_image, :style => "display:inline" %>
          </div>
          <br />
          <% end %>
          <%= f.file_field :image %>
          <%= f.hidden_field :image_cache %>
        </div>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span7 drop-shadow lifted description-input">

      <div class="row-fluid">
        <div class="field">
          <%= f.label :name,:style => "display:inline" %>*
          <%= f.text_field :name %>
        </div>
      </div>
      <div class="row-fluid">
        <div class="field">
          <%= f.label :description,:style => "display:inline" %>*
          <%= f.text_area :description %>
        </div>
      </div>

    </div>



    <div class="span4 drop-shadow lifted description-input">

      <div class="field">
        <%= f.label :event_date, :style => "display:inline" %>*
        <%= f.text_field :event_date %>
      </div>
      <div class="field input-small">
        <%= f.label :start_time, :style => "display:inline" %>*
        <%= f.time_select :start_time, {:minute_step => 5, :ampm => true} %>
      </div>
      <div class="field input-small">
        <%= f.label :end_time %>
        <%= f.time_select :end_time, {:minute_step => 5, :ampm => true} %>
      </div>

      <div class="field">
        <%= f.fields_for :location do |ff| %>
        <div>
          <%= ff.label :address, 'Location', :style => "display:inline" %>*
          <%= ff.text_field :address %>
        </div>
        <% end %>
      </div>

    </div>
  </div>


  <div class="row-fluid">
    <div class="span11" style="margin-top:-26px">
      <%= f.submit 'Submit', :class => "btn btn-large btn-success" %>
      <%= link_to 'Cancel', events_path, :class => "btn btn-large btn-danger" %>
    </div>
  </div>
  <% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<div class="row">
  <div class="span6 top-page"><h1>Events</h1></div>
    <div class="span6 top-page"><%= link_to 'Create New Event', new_event_path, :class => "btn btn-custom pull-right" %></div>
</div>

<div class ="row"  id="masonry-container">
  <div class="page">
    <% unless @events.empty? %>
      <%= render :partial => "event", :collection => @events %>
    <% else %>
      <div class="span12"><p>Sorry, no events here right now. <%= link_to "Add your own?", new_event_path, :class => "custom-link" %></p></div>    
    <% end %>  
  </div>
</div>

<script type="text/javascript">
(function() {
  var page = 1, 
      loading = false;

  function nearBottomOfPage() {
    return $(window).scrollTop() > $(document).height() - $(window).height() - 150;
  }

  $(window).scroll(function(){
    if (loading) {
      return;
    }

    if(nearBottomOfPage()) {
      loading=true;
      page++;
      $.ajax({
        url: '/events?page=' + page,
        type: 'get',
        dataType: 'script',
        success: function() {
          if (page <= <%= @events.num_pages %>) {
            $(window).sausage('draw');
            loading=false;
          } else {
            $(window).sausage('destroy');
          }
        }
        
      });
      $(".event").imagesLoaded(function(){ 
        $("#masonry-container").masonry('reload');
      });
    }
  });
  $(window).sausage();
}());
$(document).ready(function () {
 $(".event").imagesLoaded(function(){ 
  $("#masonry-container").imagesLoaded(function(){
    $("#masonry-container").masonry({
      itemSelector: '.event',
      isAnimated: true,
      columnWidth: function( containerWidth ) {
        var width = $(window).width();
        var col = 200; 
        if(width < 1200 && width >= 980) {
          col = 160;
        }
        else if(width < 980 && width >= 768) {
          col = 124;
        }
        return col;
      }
    });
  });
 });

  
});

</script>

app/views/events/index.js.erb
var $boxes = $("<div class='page'><%= escape_javascript(render(:partial => 'event', :collection => @events)) %></div>");
$("#masonry-container").append( $boxes ).masonry( 'appended', $boxes,true );

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<% provide(:title, 'Event Info') %>

<%# Google Maps Javascript API Version 3 %>

<script type="text/javascript"
src="http://maps.googleapis.com/maps/api/js?sensor=false">
</script>

<script type="text/javascript">
function initialize() {
  var mapOptions = {
    center: new google.maps.LatLng(<%= @location.latitude %>, <%= @location.longitude %>),
    zoom: 15,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById("map-canvas"),
    mapOptions);
  var marker = new google.maps.Marker({position: mapOptions.center, map: map});
}
google.maps.event.addDomListener(window, 'load', initialize);
</script>

<body onload="initialize()">

<div class="row-fluid">

  <div class="span12 top-page">
    <h1><%= @event.name %></h1>
  </div>

</div>

<div class="row-fluid">
  <div class="span8">
    
    <div class="drop-shadow lifted">
      <%= image_tag @event.image_url.to_s%>
    </div>

    <% if @event.location.address? %>
    <div class="drop-shadow lifted description">
      <div class="map-holder">
        <div id="map-canvas"></div>
      </div>
      <div style="display:inline-block; vertical-align:top;width: 33%;">
        <h3 style="margin:0px 0px 8px 8px;">Location</h3>
        <p style="margin-left:8px;"><%= @event.location.address %></p>
        <a class="btn mapsbutton" href="https://maps.google.com/maps?daddr=<%= @event.location.address %>" target="_blank"><%= image_tag 'google-maps.png', class: "brand", :style => "margin-right:10px;" %>Get Directions</a>
      </div>
    </div>
    <% end %>
  </div>

  <div class="span4 drop-shadow lifted description">
    <h3>Description</h3>
    <p><%= @event.description %></p>

    <h3>Date</h3>
    <p><%= @event.event_date %></p>

    <h3>Start Time</h3>
    <p><%= @event.start_time.strftime('%I:%M %p') %></p>
    <% if(!@event.end_time.nil?) %>
     <h3>End Time</h3>
     <p><%=  @event.end_time.strftime('%I:%M %p') %></p>
    <% end %>
    <div>
      <%= link_to 'Host Profile',User.find(@event.user_id), class: "btn btn-medium btn-success", style: "margin:8px 4px 8px 0px;" %>
      <% if signed_in? %>
        <% if current_user?(@event.user) %>
          <%= link_to 'Edit', edit_event_path(@event), class: "btn btn-medium btn-primary", style: "margin:8px 0px 8px 0px;" %>
          <%= link_to 'Delete', event_path(@event), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-medium btn-danger", style: "margin:8px 2px 8px 4px;" %>
        <% elsif current_user.admin? %>
          <%= link_to 'Delete', event_path(@event), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-medium btn-danger", style: "margin:8px 2px 8px 4px;" %>
          <%= link_to 'Contact Host', new_user_message_path(User.find(@event.user_id)), class: "btn btn-large btn-block btn-success" %>
        <%else%>
          <%= link_to 'Contact Host', new_user_message_path(User.find(@event.user_id)), class: "btn btn-large btn-block btn-success" %>
          <%= link_to 'Flag', new_event_flag_path(@event), class: "btn btn-medium btn-block btn-primary" %>
        <%end%>
      <% else %>
        <%= link_to 'Contact Host', new_user_message_path(User.find(@event.user_id)), class: "btn btn-large btn-block btn-success" %>
      <% end %>
    </div>
  </div>
</div>