config/routes.rb
Hub::Application.routes.draw do

  resources :old_items

  get "home/index"
  post "home/contact_create"

  get "statistics/user"
  get "statistics/media"
  
  put "admin/ban_user"
  put "admin/update_preferences"

  resources :users do
    resources :flags, only: [:index, :new, :create, :destroy]
    resources :messages, only: [:new, :create]
    
    member do
      put :check_confirm_code
      put :validate_pwd_change
    end   
  end

  resources :admin do
    collection do
      get 'flagged_events'
      get 'flagged_items'
      get 'flagged_projects'
      get 'flagged_users'
      get 'banned_users'
    end
  end

  resources :events do
    resources :flags, only: [:index, :new, :create, :destroy]
  end

  resources :items do
    collection do
      get 'myItems'
    end
    resources :flags, only: [:index, :new, :create, :destroy]
  end

  resources :projects do
    resources :flags, only: [:index, :new, :create, :destroy]
  end

  resources :news
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :search, only: [:index, :new]
  resources :sessions, only: [:new, :create, :destroy]
  resources :wish_lists

  match '/search_results', to:'search#index' 
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/forgot_pass', to: 'users#password_forgot'
  match '/new_wish_list', to: 'wish_lists#new'
  match '/gallery', to: 'projects#index'
  match "/users/:id/confirm" => "users#confirm_user", as: "confirm_signup"
  match "/users/:id/change_password" => "users#change_password", as: "change_pwd"
  match "/users/:id/userItems" => "users#userItems", as: "user_items"
  match "flag/:id/delete" => "flags#destroy", :via => [:delete]
  match "/reason" => "statistics#reason_for_deletion"
  match "/deletion_results" => "statistics#deletion_results", :via => [:put]
  match "/items/?category='Appliances'" => "items#index"
  match "/items/?category='Architectural'" => "items#index"
  match "/items/?category='Cabinets'" => "items#index"
  match "/items/?category='Electrical'" => "items#index"
  match "/items/?category='Exterior Doors'" => "items#index"
  match "/items/?category='Flooring'" => "items#index"
  match "/items/?category='Furniture'" => "items#index"
  match "/items/?category='Hardware'" => "items#index"
  match "/items/?category='Heating & Cooling'" => "items#index"
  match "/items/?category='Interior Doors'" => "items#index"
  match "/items/?category='Lumber'" => "items#index"
  match "/items/?category='Masonry, Tile & Stone'" => "items#index"
  match "/items/?category='Plumbing'" => "items#index"
  match "/items/?category='Tools'" => "items#index"
  match "/items/?category='Windows'" => "items#index"
  match "/items/?category='Other'" => "items#index"

  match '/contact', to:'home#contact', :via => [:get]
  match '/contact', to:'home#contact_create', :via => [:post]

  

  root :to => 'home#index'
  match "*a", to:'home#not_found' 

end

app/models/news.rb
# app/models/news.rb

# For profanity filtering
require 'obscenity/active_model'

class News < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content, :image, :image_cache, :remove_image, :title

  # For uploading images
  mount_uploader :image, ImageUploader

  # Data validation
  validates :title, :presence => true, :length => { :maximum => 255 }
  validates :content, :presence => true
end

app/controllers/news_controller.rb
# app/controllers/news_controller.rb

class NewsController < ApplicationController
  before_filter :authenticate
  # Check to see if the current request is coming from an admin user
  before_filter :admin_user, only: [:new, :create, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  # Display all news
  def index
    # Find all news from the DB
    @news = News.all
    @news.sort!{|a,b| b.created_at <=> a.created_at}

    @items = Kaminari.paginate_array(@news).page(params[:page]).per(3)
    
    respond_to do |format|
      format.js
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /news/1
  # GET /news/1.json
  # Display specific news
  def show
    # Find news from the DB
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  # New News
  def new
    # Create new news
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  # Edit News
  def edit
    # Find news in DB
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  # Create News
  def create
    # Get current user
    @user = current_user
    # Create news using the parameters from the user's request
    @news = @user.news.build(params[:news])

    respond_to do |format|
      # Save the news
      # Case 1: News saved
      if @news.save
        # Redirect the user to the news details (show) page
        # Display success message
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      # Case 2: News not saved
      else
        # Render new news form and display any errors
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  # Update News
  def update
    # Find news in DB
    @news = News.find(params[:id])

    respond_to do |format|
      # Update news
      # Case 1: News updated
      if @news.update_attributes(params[:news])
        # Redirect the user to the news details (show) page
        # Display success message
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      # Case 2: News not updated
      else
        # Render the edit news form and display any errors
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  # Delete News
  def destroy
    # Find news in DB
    @news = News.find(params[:id])
    # Delete news
    @news.destroy

    respond_to do |format|
      # Redirect the user to the news index page
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end

  # Redirect current user to the news index page unless the user is an admin
  def admin_user
    redirect_to(news_index_path) unless is_admin?
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
<%= render 'shared/news_error_messages' %>

<%= tinymce %>

<div class="row-fluid">
  <div class="span7 item">
    <div class="drop-shadow lifted">
      <div class="field">
        <%= f.label :image %>
        <% if @news.image? %>
        <%= image_tag(@news.image_url) %>
        <div>
          <br />
          <%= f.check_box :remove_image %>
          <%= f.label :remove_image, :style => "display:inline" %>
        </div>
        <br />
        <% end %>
        <%= f.file_field :image %>
        <%= f.hidden_field :image_cache %>
      </div>
    </div>
  </div>
</div>


<div class="row-fluid">
  <div class="span9 drop-shadow lifted description-input">
    <div class="row-fluid">
      <div class="field span11">
        <%= f.label :title, 'Headline' %>
        <%= f.text_field :title %>
      </div>
    </div>
    <div class="row-fluid">
      <div class="field span11">
        <%= f.label :content, 'Article Body' %>
        <%= f.text_area :content, :class => "tinymce" %>
      </div>
    </div>
  </div>
</div>

<div class="row-fluid">
  <div class="span11" style="margin-top:-10px">
    <%= f.submit 'Submit', :class => "btn btn-large btn-success" %>
    <%= link_to 'Cancel', news_index_path, :class => "btn btn-large btn-danger" %>
  </div>
</div>
<% end %>

app/views/news/_item.html.erb
<div class="span12 item">
  <div class="drop-shadow lifted">
    <h1><%= item.title %></h1>
    <h2>by <%= User.find(item.user_id).name %></h2>
    <p style="color:#777777 !important;"><%= item.created_at.strftime('%a %b %d %Y %I:%M %p') %></p>
    <% if item.updated_at != item.created_at %>
    <p style="color:#999999 !important;">Updated: <%= item.updated_at.strftime('%a %b %d %Y %I:%M %p') %></p>
    <% end %>
    <% if item.image? %>
    <p><%= image_tag item.image_url.to_s %></p>
    <% end %>
    <p><%= raw item.content %></p>
    <p><%= link_to 'Read', news_path(item), class: "btn btn-medium btn-success", style: "margin:2px 2px 2px 2px;" %>
    <% if signed_in? %>
     <% if current_user.admin? %>
        <%= link_to 'Delete', news_path(item), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-medium btn-danger pull-right", style: "margin:2px 2px 2px 2px;" %>
        <%= link_to 'Edit', edit_news_path(item), class: "btn btn-medium btn-primary pull-right", style: "margin:2px 2px 2px 2px;" %>
     <% end %>
    <%end%>
    </p>
  </div>
</div>

app/views/news/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/news/index.html.erb
<div class="row-fluid">

  <% if signed_in? %>
    <% if current_user.admin? %>
      <div class="span6 top-page"><h1>News</h1></div>
      <div class="span6 top-page"><%= link_to 'Add Article', new_news_path, :class => "btn btn-custom pull-right"  %></div>
    <% else %>
      <div class="span12 top-page"><h1>News</h1></div>
    <% end %>
  <% else %>
    <div class="span12 top-page"><h1>News</h1></div>
  <% end %>

</div>

<div class="row" id="masonry-container">
  <div class="page">
    <% unless @items.empty? %>
      <%= render :partial => "item", :collection => @items  %>
    <% else %>
      <div class="span12"><p>Sorry, no news here right now. </p></div>    
    <% end %> 
  </div>
</div>

<script type="text/javascript">
(function() {
  var page = 1, 
      loading = false;

  function nearBottomOfPage() {
    return $(window).scrollTop() > $(document).height() - $(window).height() - 150;
  }

  $(window).scroll(function(){
    if (loading) {
      return;
    }

    if(nearBottomOfPage()) {
      loading=true;
      page++;
      $.ajax({
        url: "/news?page=" + page,
        type: 'get',
        dataType: 'script',
        success: function() {
          if (page <= <%= @items.num_pages %>) {
            $(window).sausage('draw');
            loading=false;
          } else {
            $(window).sausage('destroy');
          }
        }
        
      });
      $(".item").imagesLoaded(function(){ 
        $("#masonry-container").masonry('reload');
      });
    }
  });
  $(window).sausage();
}());
$(document).ready(function () {
 $(".item").imagesLoaded(function(){ 
  $("#masonry-container").imagesLoaded(function(){
    $("#masonry-container").masonry({
      itemSelector: '.item',
      isAnimated: true,
      columnWidth: function( containerWidth ) {
        var width = $(window).width();
        var col = 200; 
        if(width < 1200 && width >= 980) {
          col = 160;
        }
        else if(width < 980 && width >= 768) {
          col = 124;
        }
        return col;
      }
    });
  });
 });

  
});

</script>

app/views/news/index.js.erb
var $boxes = $("<div class='page'><%= escape_javascript(render(:partial => 'item', :collection => @items)) %></div>");
$("#masonry-container").append( $boxes ).masonry( 'appended', $boxes,true );

app/views/news/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

app/views/news/show.html.erb
<% provide(:title, 'news info') %>
<div class="row-fluid">

  <div class="span12 top-page">
    <h1><%= @news.title %></h1>
    <h2>by <%= User.find(@news.user_id).name %></h2>
    <p><%= link_to 'Back', news_index_path, class: "btn btn-medium btn-danger", style: "margin:2px 2px 2px 0px;" %></p>
    </div>

</div>

<div class="row-fluid">
  <div class="span12">
    <div class="drop-shadow lifted">
    <% if @news.image? %>
    <p><%= image_tag @news.image_url.to_s %></p>
    <% end %>
    <p><%= raw @news.content %></p>
    <p>
    	<% if signed_in? %>
 			<% if current_user?(@news.user) %>
				<%= link_to 'Edit', edit_news_path(@news), class: "btn btn-medium btn-primary", style: "margin:2px 2px 2px 2px;" %>
				<%= link_to 'Delete', news_path(@news), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-medium btn-danger", style: "margin:2px 2px 2px 2px;" %>
 			<% elsif current_user.admin? %>
				<%= link_to 'Delete', news_path(@news), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-medium btn-danger", style: "margin:2px 2px 2px 2px;" %>
 			<%else%>
        <%= link_to 'Contact Author', new_user_message_path(User.find(@news.user_id)), class: "btn btn-medium btn-success", style: "margin:2px 2px 2px 2px;" %>
 			<% end %>
		<% end %>
  	</p>
  </div>
  </div>
</div>