config/routes.rb
Hub::Application.routes.draw do

  resources :old_items

  get "home/index"
  post "home/contact_create"

  get "statistics/user"
  get "statistics/media"
  
  put "admin/ban_user"
  put "admin/update_preferences"

  resources :users do
    resources :flags, only: [:index, :new, :create, :destroy]
    resources :messages, only: [:new, :create]
    
    member do
      put :check_confirm_code
      put :validate_pwd_change
    end   
  end

  resources :admin do
    collection do
      get 'flagged_events'
      get 'flagged_items'
      get 'flagged_projects'
      get 'flagged_users'
      get 'banned_users'
    end
  end

  resources :events do
    resources :flags, only: [:index, :new, :create, :destroy]
  end

  resources :items do
    collection do
      get 'myItems'
    end
    resources :flags, only: [:index, :new, :create, :destroy]
  end

  resources :projects do
    resources :flags, only: [:index, :new, :create, :destroy]
  end

  resources :news
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :search, only: [:index, :new]
  resources :sessions, only: [:new, :create, :destroy]
  resources :wish_lists

  match '/search_results', to:'search#index' 
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/forgot_pass', to: 'users#password_forgot'
  match '/new_wish_list', to: 'wish_lists#new'
  match '/gallery', to: 'projects#index'
  match "/users/:id/confirm" => "users#confirm_user", as: "confirm_signup"
  match "/users/:id/change_password" => "users#change_password", as: "change_pwd"
  match "/users/:id/userItems" => "users#userItems", as: "user_items"
  match "flag/:id/delete" => "flags#destroy", :via => [:delete]
  match "/reason" => "statistics#reason_for_deletion"
  match "/deletion_results" => "statistics#deletion_results", :via => [:put]
  match "/items/?category='Appliances'" => "items#index"
  match "/items/?category='Architectural'" => "items#index"
  match "/items/?category='Cabinets'" => "items#index"
  match "/items/?category='Electrical'" => "items#index"
  match "/items/?category='Exterior Doors'" => "items#index"
  match "/items/?category='Flooring'" => "items#index"
  match "/items/?category='Furniture'" => "items#index"
  match "/items/?category='Hardware'" => "items#index"
  match "/items/?category='Heating & Cooling'" => "items#index"
  match "/items/?category='Interior Doors'" => "items#index"
  match "/items/?category='Lumber'" => "items#index"
  match "/items/?category='Masonry, Tile & Stone'" => "items#index"
  match "/items/?category='Plumbing'" => "items#index"
  match "/items/?category='Tools'" => "items#index"
  match "/items/?category='Windows'" => "items#index"
  match "/items/?category='Other'" => "items#index"

  match '/contact', to:'home#contact', :via => [:get]
  match '/contact', to:'home#contact_create', :via => [:post]

  

  root :to => 'home#index'
  match "*a", to:'home#not_found' 

end

app/models/project.rb
# app/models/project.rb

# For profanity filtering
require 'obscenity/active_model'

class Project < ActiveRecord::Base
  belongs_to :user
  has_many :flags, :as => :flaggable, :dependent => :destroy

  attr_accessible :description, :image, :image_cache, :remove_image, :name

  # For uploading images
  mount_uploader :image, ImageUploader

  # String sanitization
  before_validation :sanitize_project

  # Data validation
  validates :user_id, :presence => true
  validates :name, :presence => true, :obscenity => true, :length => { :maximum => 255 }
  validates :description, :presence => true, :obscenity => true

  def sanitize_project
    # Sanitize project fields unless the field is blank
  	self.name = Sanitize.clean(self.name).gsub('&amp;','&').gsub('&gt;', '>') unless self.name.blank?
    self.description = Sanitize.clean(self.description).gsub('&amp;','&').gsub('&gt;', '>') unless self.description.blank?
  end
  
end

app/controllers/projects_controller.rb
# app/controllers/projects_controller.rb

class ProjectsController < ApplicationController
  before_filter :authenticate
  before_filter :signed_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :can_destroy, only: [:destroy]

  # GET /projects
  # GET /projects.json
  # Display all projects
  def index
    @projects = Project.all
    @projects.sort!{|a,b| b.created_at <=> a.created_at}
    
    @items = Kaminari.paginate_array(@projects).page(params[:page]).per(1)
    
    respond_to do |format|
      format.js
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  # Display a specific project
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  # Create a new project (form)
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  # Edit an existing project (form)
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  # Create a new project (process request)
  def create
    @user = current_user
    @project = @user.projects.build(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  # Update an existing project
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  # Delete a project
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private

    # Check if the current user is the owner of the requested project
    def correct_user
      @project = Project.find(params[:id])
      redirect_to(projects_path) unless current_user?(@project.user)
    end

    # Check if the current user has permission to delete the requested project
    def can_destroy
      @project = Project.find(params[:id])
      redirect_to(projects_path) unless current_user?(@project.user) || current_user.admin?
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<h2>(*) Required Fields<h2>

  <%= form_for(@project) do |f| %>
  <%= render 'shared/project_error_messages' %>


  <div class="row-fluid">
    <div class="span7 item">
      <div class="drop-shadow lifted">
        <div class="field">
          <%= f.label :image %>
          <% if @project.image? %>
          <%= image_tag(@project.image_url) %>
          <div>
            <br />
            <%= f.check_box :remove_image %>
            <%= f.label :remove_image, :style => "display:inline" %>
          </div>
          <br />
          <% end %>
          <%= f.file_field :image %>
          <%= f.hidden_field :image_cache %>
        </div>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span9 drop-shadow lifted description-input">
      <div class="row-fluid">
        <div class="field">
          <%= f.label :name, 'Project Name', :style => "display:inline"  %>*
          <%= f.text_field :name %>
        </div>
      </div>
      <div class="row-fluid">
        <div class="field">
          <%= f.label :description, 'Description', :style => "display:inline"  %>*
          <%= f.text_area :description %>
        </div>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span11" style="margin-top:-10px">
      <%= f.submit 'Submit', :class => "btn btn-large btn-success" %>
      <%= link_to 'Cancel', projects_path, :class => "btn btn-large btn-danger" %>
    </div>
  </div>
  <% end %>

app/views/projects/_item.html.erb
<div class="span12 item">
  <div class="drop-shadow lifted">
    <h1><%= item.name %></h1>
    <h2>by <%= User.find(item.user_id).name %></h2>
    <p><%= image_tag item.image_url.to_s %></p>
    <p><%= item.description %></p>
    <p><%= link_to 'View', item, class: "btn btn-medium btn-success", style: "margin:2px 2px 2px 2px;" %>
    <% if signed_in? %>
     <% if current_user.admin? %>
      <%= link_to 'Delete Project', item, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-medium btn-danger pull-right", style: "margin:2px 2px 2px 2px;" %>
     <% end %>
    <%end%>
  </p>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class="row">
  <div class="span6 top-page"><h1>Gallery</h1><h2>Showcasing Deco Hub Projects</h2></div>
    <div class="span6 top-page"><%= link_to 'Submit Project', new_project_path, :class => "btn btn-custom pull-right" %></div>
</div>

<div class="row" id="masonry-container">
  <div class="page">
    <% unless @items.empty? %>
      <%= render :partial => "item", :collection => @items  %>
    <% else %>
      <div class="span12"><p>Sorry, no items here right now. </p></div>    
    <% end %> 
  </div>
</div>

<script type="text/javascript">
(function() {
  var page = 1, 
      loading = false;

  function nearBottomOfPage() {
    return $(window).scrollTop() > $(document).height() - $(window).height() - 150;
  }

  $(window).scroll(function(){
    if (loading) {
      return;
    }

    if(nearBottomOfPage()) {
      loading=true;
      page++;
      $.ajax({
        url: "/gallery?page=" + page,
        type: 'get',
        dataType: 'script',
        success: function() {
          if (page <= <%= @items.num_pages %>) {
            $(window).sausage('draw');
            loading=false;
          } else {
            $(window).sausage('destroy');
          }
        }
        
      });
      $(".item").imagesLoaded(function(){ 
        $("#masonry-container").masonry('reload');
      });
    }
  });
  $(window).sausage();
}());
$(document).ready(function () {
 $(".item").imagesLoaded(function(){ 
  $("#masonry-container").imagesLoaded(function(){
    $("#masonry-container").masonry({
      itemSelector: '.item',
      isAnimated: true,
      columnWidth: function( containerWidth ) {
        var width = $(window).width();
        var col = 200; 
        if(width < 1200 && width >= 980) {
          col = 160;
        }
        else if(width < 980 && width >= 768) {
          col = 124;
        }
        return col;
      }
    });
  });
 });

  
});

</script>

app/views/projects/index.js.erb
var $boxes = $("<div class='page'><%= escape_javascript(render(:partial => 'item', :collection => @items)) %></div>");
$("#masonry-container").append( $boxes ).masonry( 'appended', $boxes,true );

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<% provide(:title, 'project info') %>

<div class="row-fluid">

  <div class="span12 top-page">
    <h1><%= @project.name %></h1>
  </div>

</div>

<div class="row-fluid">
  <div class="span8">
   <div class="drop-shadow lifted">
      <%= image_tag @project.image_url.to_s%>
   </div>
  </div>
  
   <div class="span4 drop-shadow lifted description">
     <h3>Description</h3>
     <p><%= @project.description %></p>

    <p><% if signed_in? %>
       <% if current_user?(@project.user) %>
	<%= link_to 'Edit', edit_project_path(@project), class: "btn btn-medium btn-primary", style: "margin:2px 2px 2px 2px;" %>
	<%= link_to 'Delete', project_path(@project), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-medium btn-danger", style: "margin:2px 2px 2px 2px;" %>
       <% elsif current_user.admin? %>
	<%= link_to 'Delete', project_path(@project), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-medium btn-danger", style: "margin:2px 2px 2px 2px;" %>
        <%= link_to 'Contact author', new_user_message_path(User.find(@project.user_id)), class: "btn btn-medium btn-success", style: "margin:2px 2px 2px 2px;" %>
       <%else%>
        <%= link_to 'Flag', new_project_flag_path(@project), class: "btn btn-medium btn-primary", style: "margin:2px 2px 2px 2px;" %>
        <%= link_to 'Contact author', new_user_message_path(User.find(@project.user_id)), class: "btn btn-medium btn-success", style: "margin:2px 2px 2px 2px;" %>
      <% end %>
   <% end %>
  <%= link_to 'Author Profile',User.find(@project.user_id), class: "btn btn-medium btn-success", style: "margin:2px 2px 2px 2px;"%>
   </p>

 </div>
</div>